CREATE DATABASE ORGANISER


USE ORGANISER

DROP TABLE users
CREATE TABLE users (
  id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  email VARCHAR(150) NOT NULL,
  usuario varchar(60) NOT NULL,
  senha varchar(MAX) NOT NULL,
  createdAt DATETIME NOT NULL,
  updateAt DATETIME NOT NULL
)